### ISSUE TITLE
/src/Facade/Validate实现Bootstrap接口

### ISSUE THREAD

**Issue by iYting** [Tinywan/webman-validate#9]
大佬 最近在学习你的代码，发现有个不懂的地方：/src/Facade/Validate 这个门面 为什么要implements这个Bootstrap接口啊？
我自己写的门面类 不implements这个接口也可以用，implements了bootstrap接口是有啥优点吗?

**Comment by Tinywan** [comment]
这个插件是很早的时候写的，实现Bootstrap接口可以在进程启动的时候实例化类`static::$_instance = new \Tinywan\Validate\Validate();`
